<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
  </PropertyGroup> 

  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" />
    <Reference Include="UnityEngine.CoreModule" HintPath="/mnt/Disk3/SteamLibrary/steamapps/common/SCP Secret Laboratory Dedicated Server/SCPSL_Data/Managed/UnityEngine.CoreModule.dll" />
  </ItemGroup>

</Project>
